require("after.plugin.color")
require("after.plugin.gitsigns")
require("after.plugin.guess-indent")
require("after.plugin.harpoon")
require("after.plugin.lualine")
require("after.plugin.mini")
require("after.plugin.nvim-tree")
require("after.plugin.startify")
require("after.plugin.telescope")
require("after.plugin.todo-comments")
require("after.plugin.undotree")
require("after.plugin.indent-blankline")

require("after.lang")
