require("after.plugin.color")
require("after.plugin.gitsigns")
require("after.plugin.harpoon")
require("after.plugin.lualine")
require("after.plugin.mini")
require("after.plugin.nvim-tree")
require("after.plugin.persistence")
require("after.plugin.telescope")
require("after.plugin.todo-comments")
require("after.plugin.undotree")

require("after.lang")
